@rootURL = https://localhost:7167

GET {{rootURL}}/api/Post
Accept: application/json

###
GET {{rootURL}}/api/Post/2
Accept: application/json
###

POST {{rootURL}}/api/Post
Content-Type: application/json