// <auto-generated />
using System;
using BoardTroveAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardTroveAPI.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20250721213527_post_poly2")]
    partial class post_poly2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardTroveAPI.Models.BasePost", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("post_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasDiscriminator<string>("post_type").HasValue("post_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BoardTroveAPI.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PfpLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BoardTroveAPI.Models.FENPost", b =>
                {
                    b.HasBaseType("BoardTroveAPI.Models.BasePost");

                    b.Property<string>("FEN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("post_fen");
                });

            modelBuilder.Entity("BoardTroveAPI.Models.PGNPost", b =>
                {
                    b.HasBaseType("BoardTroveAPI.Models.BasePost");

                    b.Property<string>("PGN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("post_pgn");
                });
#pragma warning restore 612, 618
        }
    }
}
